apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins-test
  labels:
    jenkins/label: jenkins-wizzz-jenkins-agent
spec:
  containers:
  - name: docker
    image: wizzzuveye/docker-python-demo
    command:
    - cat
    securityContext:
      privileged: true
    tty: true
    resources:
      requests:
        memory: "2Gi"  # Minimum memory this container is guaranteed
        cpu: "1000m"   # Minimum CPU this container is guaranteed (1000m = 1 CPU core)
      limits:
        memory: "4Gi"  # Maximum memory the container can use
        cpu: "2000m"
  - name: kubectl
    image: lachlanevenson/k8s-kubectl:latest
    command:
    - cat
    securityContext:
      privileged: true
    tty: true
    # volumeMounts:
    # - name: workspace-volume
    #   mountPath: /home/jenkins/agent
  # volumes:
  # - name: workspace-volume
  #   emptyDir: {}
