apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins-test
  labels:
    jenkins/label: jenkins-wizzz-jenkins-agent
spec:
  containers:
  - name: docker
    image: wizzzuveye/docker-python-demo
    command:
    - cat
    securityContext:
      privileged: true
    tty: true
  - name: kubectl
    image: lachlanevenson/k8s-kubectl:latest
    command:
    - cat
    securityContext:
      privileged: true
    tty: true
    # volumeMounts:
    # - name: workspace-volume
    #   mountPath: /home/jenkins/agent
  # volumes:
  # - name: workspace-volume
  #   emptyDir: {}
