apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/label: jenkins-wizzz-jenkins-agent
spec:
  containers:
  - name: docker
    image: docker:24.0.5
    command:
    - cat
    securityContext:
      privileged: true
    tty: true
    # volumeMounts:
    # - name: workspace-volume
    #   mountPath: /home/jenkins/agent
  # volumes:
  # - name: workspace-volume
  #   emptyDir: {}
