apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/label: jenkins-wizzz-jenkins-agent
spec:
  containers:
  - name: python
    image: python:3.9-slim
    command:
    - cat
    tty: true
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  - name: docker
    image: docker:latest
    command:
    - cat
    securityContext:
      privileged: true
    tty: true
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
    - name: docker-socket-volume
      mountPath: /var/run/docker.sock
  volumes:
  - name: workspace-volume
    emptyDir: {}
  - name: docker-socket-volume
    hostPath:
      path: /var/run/docker.sock
